source 'https://rubygems.org'
ruby '2.4.4'

gem 'bootsnap', require: false
gem 'devise'
gem 'jbuilder', '~> 2.0'
gem 'pg', '~> 0.21'
gem 'puma'
gem 'rails', '5.2.0'
gem 'redis'
gem 'cocoon'
gem 'autoprefixer-rails'
gem 'font-awesome-sass', '~> 5.0.9'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem 'webpacker'
gem 'bootstrap', '~> 4.1', '>= 4.1.1'
gem 'jquery-rails'
gem 'searchkick'
gem 'cloudinary'
gem 'carrierwave', '~> 1.2'
gem 'acts_as_follower', github: 'tcocca/acts_as_follower', branch: 'master'
gem 'public_activity'
gem 'link_thumbnailer'
gem 'acts_as_votable', '~> 0.11.1'
gem 'social-share-button'
gem 'friendly_id', '~> 5.2.0'
group :development do
  gem 'web-console', '>= 3.3.0'
end

group :development, :test do
  gem 'dotenv-rails'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
